volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
  nc-data:
    driver: local

services:
  traefik:
    extends:
      file: ./traefik/traefik-compose.yml
      service: traefik
    networks:
      - traefik-proxy
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}

  nextcloud:
    extends:
      file: ./nextcloud/nextcloud-compose.yml
      service: nextcloud
    networks:
      - traefik-proxy
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nc-data:/home/gekko/NC-gekko/nextcloud/data
    environment:
      - APACHE_PORT=11000
      - NEXTCLOUD_DATADIR=/home/gekko/NC-gekko/nextcloud/data/nc-data
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.mentolder.de`)
      - traefik.http.routers.nextcloud.entrypoints=https
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.routers.nextcloud.tls.certresolver=cloudflare
      - traefik.http.services.nextcloud.loadbalancer.server.port=11000

networks:
  traefik-proxy:
    driver: bridge
    external: false
