version: '3.8'

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    volumes:
      - ${NEXTCLOUD_HTML_VOLUME}:/var/www/html
      - ${NEXTCLOUD_CUSTOM_APPS_VOLUME}:/var/www/html/custom_apps
      - ${NEXTCLOUD_CONFIG_VOLUME}:/var/www/html/config
      - ${NEXTCLOUD_DATA_VOLUME}:/var/www/html/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
      - TRUSTED_PROXIES=${NEXTCLOUD_TRUSTED_PROXIES}
    depends_on:
      - db
      - redis
    networks:
      - nextcloud_network

  db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: nextcloud_db
    restart: unless-stopped
    command:
      - --transaction-isolation=READ-COMMITTED
      - --binlog-format=ROW
      - --innodb-file-per-table=1
      - --skip-innodb-read-only-compressed
    volumes:
      - ${MARIADB_DATA_DIR}:/config
      - ${MARIADB_BACKUP_DIR}:/backup
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_INITDB_SKIP_TZINFO=1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nextcloud_network

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    networks:
      - nextcloud_network

  coturn:
    image: coturn/coturn
    container_name: coturn
    restart: unless-stopped
    networks:
      - docker_public_net
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "49160-49200:49160-49200/udp"
    command: >
      -n --log-file=stdout
      --min-port=49160 --max-port=49200
      --external-ip=2a0f:ff00:2dc:1fc0::10
      --lt-cred-mech --fingerprint
      --no-multicast-peers --no-cli
      --no-tlsv1 --no-tlsv1_1
      --realm=korczewski.de

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${SWAG_URL}
      - SUBDOMAINS=${SWAG_SUBDOMAINS}
      - VALIDATION=${SWAG_VALIDATION}
      - DNSPLUGIN=${SWAG_DNSPLUGIN}
      - ONLY_SUBDOMAINS=false
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
    volumes:
      - ${SWAG_CONFIG_VOLUME}:/config
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    networks:
      - docker_public_net
      - nextcloud_network
    depends_on:
      - nextcloud
      - db
      - redis

networks:
  docker_public_net:
    driver: bridge
    enable_ipv6: true
  nextcloud_network:
    driver: bridge
