services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TunnelToken=${TUNNEL_TOKEN}
    volumes:
      - /home/patrick/NC-gekko/config:/etc/cloudflared/config:ro
      - /home/patrick/NC-gekko/.env:/app/.env
    networks:
      - traefik_net
    restart: unless-stopped
networks:
  traefik_net:
    external: true

###############################################################################


  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}

  app:
    image: nextcloud:latest
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD_File}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.mentolder.de`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

services:
services:
  traefik:
    image: traefik:latest
    command:
      - "--configfile=/etc/traefik/traefik.yml"
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/patrick/NC-gekko/traefik/data/traefik.yml:/etc/traefik/traefik.yml:ro
      - traefik-data:/home/patrick/NC-gekko/traefik/data/
      - traefik-data:/home/patrick/NC-gekko/traefik/data/certificates.yml:/etc/traefik/certificates.yml:ro
      - traefik-data:/home/patrick/NC-gekko/traefik/data/origin-certificates:/etc/traefik/origin-certificates:ro
    networks:
      - traefik_net
      - traefik_internal
    restart: unless-stopped

networks:
  traefik_internal:
    external: true
  traefik_net:
    external: true

volumes:
  traefik-data:
volumes:
  nextcloud:
  db:
    services:
      vaultwarden:
        image: traefik/whoami
        container_name: whoami
        restart: always
        labels:
          - traefik.enable=true
          - traefik.http.routers.whoami.rule=Host(`whoami.korczewski.de.tld`)
          - traefik.http.routers.whoami.entrypoints=websecure
          - traefik.http.routers.whoami.tls=true
          - traefik.http.routers.whoami.service=whoami
          - traefik.http.services.whoami.loadbalancer.server.port=80
        networks:
          - traefik_internal
    networks:
      traefik_internal:
        external: true