version: '3.8'
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    volumes:
      - ./nextcloud/html:/var/www/html
      - ./nextcloud/custom_apps:/var/www/html/custom_apps
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=170591pk
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=170591pk
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - nextcloud_network

  db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: nextcloud_db
    restart: unless-stopped
    volumes:
      - ./mariadb/config:/config
      - ./mariadb/backup:/backup
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=170591pk
      - MYSQL_PASSWORD=170591
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud_network

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: unless-stopped
    networks:
      - nextcloud_network

  coturn:
    image: coturn/coturn
    container_name: coturn
    restart: unless-stopped
    networks:
      - nextcloud_network
    ports:
      - "3478:3478/udp"
      - "5349:5349/udp"

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=korczewski.de
      - SUBDOMAINS=wildcard
      - VALIDATION=cloudflare
    volumes:
      - ./swag:/config
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    networks:
      - nextcloud_network
    depends_on:
      - nextcloud

networks:
  nextcloud_network:
    driver: bridge