version: '3.8'

services:
  nextcloud:
    extends:
      file: ./nextcloud/nextcloud-compose.yml
      service: nextcloud
    networks:
      - nextcloud_network

  db:
    extends:
      file: ./nextcloud/nextcloud-compose.yml
      service: db
    networks:
      - nextcloud_network

  redis:
    extends:
      file: ./nextcloud/nextcloud-compose.yml
      service: redis
    networks:
      - nextcloud_network

  coturn:
    extends:
      file: ./nextcloud/nextcloud-compose.yml
      service: coturn
    network_mode: host

  swag:
    extends:
      file: ./swag/swag-compose.yml
      service: swag
    networks:
      - docker_public_net
      - nextcloud_network

networks:
  docker_public_net:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: ${NEXTCLOUD_NETWORK_SUBNET_IPV4}
          gateway: ${NEXTCLOUD_NETWORK_GATEWAY_IPV4}
        - subnet: ${NEXTCLOUD_NETWORK_SUBNET_IPV6}
          gateway: ${NEXTCLOUD_NETWORK_GATEWAY_IPV6}
  nextcloud_network:
    driver: bridge