services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: unless-stopped
    networks:
      - traefik-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/gekko/traefik/data/traefik.yml:/traefik.yml:ro
      - /home/gekko/traefik/data/config.yml:/config.yml
      - /home/gekko/traefik/data/letsencrypt:/letsencrypt
      - /home/gekko/traefik/data/traefik.log:/traefik.log
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=cloudflare
      - traefik.http.routers.traefik.tls.domains[0].main=mentolder.de
      - traefik.http.routers.traefik.tls.domains[0].sans=*.mentolder.de
      - traefik.http.routers.traefik.service=api@internal
networks:
  traefik-proxy:
    external: true