services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/gekko/NC-gekko/traefik/data/traefik.yml:/traefik.yml:ro
      - /home/gekko/NC-gekko/traefik/data/conf:/conf:ro
      - /home/gekko/NC-gekko/traefik/data/letsencrypt:/letsencrypt
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    command:
      - "--configfile=/traefik.yml"