services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    volumes:
      - ${NEXTCLOUD_HTML_VOLUME}:/var/www/html
      - ${NEXTCLOUD_CUSTOM_APPS_VOLUME}:/var/www/html/custom_apps
      - ${NEXTCLOUD_CONFIG_VOLUME}:/var/www/html/config
      - ${NEXTCLOUD_DATA_VOLUME}:/var/www/html/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
      - TRUSTED_PROXIES=${NEXTCLOUD_TRUSTED_PROXIES}
    depends_on:
      - db
      - redis
    networks:
      - nextcloud_network

  db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: nextcloud_db
    restart: unless-stopped
    command:
      - --transaction-isolation=READ-COMMITTED
      - --binlog-format=ROW
      - --innodb-file-per-table=1
      - --skip-innodb-read-only-compressed
    volumes:
      - ${MARIADB_DATA_DIR}:/config
      - ${MARIADB_BACKUP_DIR}:/backup
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_INITDB_SKIP_TZINFO=1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nextcloud_network

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    networks:
      - nextcloud_network

  coturn:
    image: coturn/coturn
    container_name: nextcloud_coturn
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${COTURN_VOLUME}:/etc/coturn
    command: [
      "-n",
      "--log-file=stdout",
      "--external-ip=$(detect-external-ip)",
      "--realm=${COTURN_REALM}",
      "--server-name=${COTURN_SERVER_NAME}",
      "--lt-cred-mech",
      "--fingerprint",
      "--no-multicast-peers",
      "--min-port=49160",
      "--max-port=49200"
    ]
    environment:
      - DETECT_EXTERNAL_IP=1
      - DETECT_RELAY_IP=1
      - DETECT_EXTERNAL_IP_COMMAND=detect-external-ip

networks:
  nextcloud_network:
    driver: bridge