version: '3.8'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    volumes:
      - ${NEXTCLOUD_HTML_VOLUME}:/var/www/html
      - ${NEXTCLOUD_CUSTOM_APPS_VOLUME}:/var/www/html/custom_apps
      - ${NEXTCLOUD_CONFIG_VOLUME}:/var/www/html/config
      - ${NEXTCLOUD_DATA_VOLUME}:/var/www/html/data
    environment:
      - MYSQL_HOST=${NEXTCLOUD_MYSQL_HOST}
      - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - REDIS_HOST=${NEXTCLOUD_REDIS_HOST}
      - TRUSTED_PROXIES=${NEXTCLOUD_TRUSTED_PROXIES}
    depends_on:
      - db
      - redis

  db:
    image: mariadb:10.5
    container_name: nextcloud_db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}

  coturn:
    image: coturn/coturn
    container_name: nextcloud_coturn
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${COTURN_VOLUME}:/etc/coturn
    command: ["-n", "--log-file=stdout", "--external-ip=$(detect-external-ip)", "--realm=${COTURN_REALM}", "--server-name=${COTURN_SERVER_NAME}", "--lt-cred-mech", "--fingerprint", "--no-multicast-peers", "--min-port=49160", "--max-port=49200"]
    environment:
      - DETECT_EXTERNAL_IP=1
      - DETECT_RELAY_IP=1
      - DETECT_EXTERNAL_IP_COMMAND=detect-external-ip