http:
  routers:
    nextcloud:
      rule: "Host(`nextcloud.mentolder.de.TLS`)"
      entrypoints:
        - "https"
      service: nextcloud
      middlewares:
        - https-redirect
        - nextcloud-secure-headers
      tls:
        domains:
          - main: "nextcloud.mentolder.de.TLS"

  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://10.0.0.3:11000"
        passHostHeader: true

  middlewares:
    nextcloud-secure-headers:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
        customResponseHeaders:
          X-Robots-Tag: "none"

    https-redirect:
      redirectscheme:
        scheme: https
        permanent: true