services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=korczewski.de
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - SUBDOMAINS=wildcard
      - ONLY_SUBDOMAINS=false
      - EMAIL=p.korczewski@gmail.com # Replace with your email
    volumes:
      - /home/patrick/NC-gekko/swag/config:/config
    ports:
      - "443:443"
    restart: unless-stopped
    networks:
      - docker_public_net

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/patrick/NC-gekko/nextcloud/config:/config
      - /home/patrick/NC-gekko/nextcloud/data:/data
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - docker_public_net

networks:
  docker_public_net:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
        - subnet: 2a0f:ff00:2dc:1fd::/64
          gateway: 2a0f:ff00:2dc:1fd::1